"""empty message

Revision ID: 89747863cc3d
Revises: 0ab2b96ac8ec
Create Date: 2023-10-03 04:37:11.842125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89747863cc3d'
down_revision = '0ab2b96ac8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answersuser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('answers', sa.String(length=250), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('isCorrect', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answersuser')
    # ### end Alembic commands ###
