"""empty message

<<<<<<<< HEAD:migrations/versions/9b2cdb27a9eb_.py
Revision ID: 9b2cdb27a9eb
Revises: 
Create Date: 2023-09-23 01:28:32.583521
========
Revision ID: b86d2ae4a9e1
Revises: 
Create Date: 2023-09-23 21:41:58.005219
>>>>>>>> e7daa099cbda20e86c7abcf59e617b9e57c9706b:migrations/versions/b86d2ae4a9e1_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/9b2cdb27a9eb_.py
revision = '9b2cdb27a9eb'
========
revision = 'b86d2ae4a9e1'
>>>>>>>> e7daa099cbda20e86c7abcf59e617b9e57c9706b:migrations/versions/b86d2ae4a9e1_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('question', sa.String(length=250), nullable=True),
    sa.Column('info_blog', sa.String(length=250), nullable=True),
    sa.Column('info_youtube', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('img', sa.String(length=400), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('document', sa.String(length=250), nullable=True),
    sa.Column('teacher', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('answers', sa.String(length=250), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('isCorrect', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('user')
    op.drop_table('token_blocked_list')
    op.drop_table('exercise')
    # ### end Alembic commands ###
